"""Add UDISE and CBSE compliance fields to profiles

Revision ID: 5a439d407a9f
Revises: 053a6689998f
Create Date: 2026-03-21 08:45:48.433414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a439d407a9f'
down_revision: Union[str, Sequence[str], None] = '053a6689998f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_user_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_user_id'], ['tenant_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_user_id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_user_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_number', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('aadhaar_number', sa.String(), nullable=True),
    sa.Column('apaar_id', sa.String(), nullable=True),
    sa.Column('caste_category', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('mother_tongue', sa.String(), nullable=True),
    sa.Column('is_cwsn', sa.Boolean(), nullable=True),
    sa.Column('residential_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_user_id'], ['tenant_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('apaar_id'),
    sa.UniqueConstraint('tenant_user_id')
    )
    op.create_table('student_guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('parent_user_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.Enum('FATHER', 'MOTHER', 'LOCAL_GUARDIAN', 'OTHER', name='guardianrelationship'), nullable=False),
    sa.Column('emergency_contact_priority', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('annual_income', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_guardians_tenant_id'), 'student_guardians', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_guardians_tenant_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_table('student_profiles')
    op.drop_table('staff_profiles')
    # ### end Alembic commands ###
